spring:
  application:
    name: api
  datasource:
    url: "jdbc:postgresql://${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DATABASE}"
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 30
      minimum-idle: 15
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
server:
  port: 8080
management:
  endpoints:
    web:
      exposure:
        include:  
        - health
        - info
        - prometheus
  prometheus:
    metrics:
      export:
        enabled: true

logging:
  level:
    root: INFO
    org:
      springframework:
        web: INFO

application:
  scheme: https
  node-public-suffix: -node
  node-private-suffix: -infra
  cloud-domain: samuelmjordan.dev

cors:
  allowed-origins:
    - https://mc-host-web-production.up.railway.app
    - http://localhost:3000

cloudflare:
  api-base: "https://api.cloudflare.com/client/v4"
  api-token: ${CLOUDFLARE_SECRET_KEY}
  origin-cert: ${CLOUDFLARE_ORIGIN_CERTIFICATE}
  private-key: ${CLOUDFLARE_CERTIFICATE_PRIVATE_KEY}

pterodactyl:
  api-base: ${PANEL_HOST}
  api-token: ${PANEL_SECRET_KEY}
  client-api-token: ${PANEL_ADMIN_CLIENT_SECRET_KEY}
  admin-user: ${PANEL_ADMIN_USER}
  admin-password: ${PANEL_ADMIN_PASSWORD}
  password-key: ${PANEL_PASSWORD_KEY}

hetzner:
  cloud:
    api-base: "https://api.hetzner.cloud/v1"
    api-token: ${HETZNER_SECRET_KEY}
  robot:
    api-base: "https://robot-ws.your-server.de"
    api-token: ${HETZNER_SECRET_KEY}

ssh:
  private-key: ${SSH_PRIVATE_KEY}
  public-key: ${SSH_PUBLIC_KEY}

clerk:
  key: ${CLERK_SECRET_KEY}
  signing-key: ${CLERK_SECRET_SIGNING_KEY}
  valid-events:
    - user.created
    - user.deleted
    - user.updated

stripe:
  api-key: ${STRIPE_SECRET_KEY}
  signing-key: ${STRIPE_SECRET_SIGNING_KEY}
  active-java-product-id: prod_RiiVxhDuwyX0qD
  event-debounce-ttl-ms: 5000
  subscription-sync-timeout-minutes: 15
  invoice-events:
    - invoice.created
    - invoice.finalized
    - invoice.voided
    - invoice.marked_uncollectible
    - invoice.paid
    - invoice.updated
    - invoice.payment_failed
    - invoice.payment_action_required
    - invoice.upcoming
  subscription-events:
    - checkout.session.completed
    - customer.subscription.created
    - customer.subscription.updated
    - customer.subscription.deleted
    - customer.subscription.paused
    - customer.subscription.resumed
    - customer.subscription.trial_will_end
    - customer.subscription.pending_update
    - customer.subscription.pending_update_applied
    - customer.subscription.pending_update_expired
    - payment_intent.succeeded
    - payment_intent.payment_failed
    - payment_intent.canceled
    - invoice.created
    - invoice.finalized
    - invoice.voided
    - invoice.marked_uncollectible
    - invoice.paid
    - invoice.updated
    - invoice.payment_failed
    - invoice.payment_action_required
    - invoice.upcoming
  price-events:
    - price.created
    - price.deleted
    - price.updated
  payment-method-events:
    - payment_method.attached
    - payment_method.updated
    - payment_method.automatically_updated

payment:
  method:
    display:
      card:
        brand:
          label: ""
          display_type: "brand_icon"
          order: 1
        last_four:
          label: "ending in"
          display_type: "masked"
          order: 2
        exp_display:
          label: "expires"
          display_type: "text"
          order: 3
      apple_pay:
        wallet_type:
          label: ""
          display_type: "wallet_icon"
          order: 1
        card_brand:
          label: ""
          display_type: "brand_icon"
          order: 2
        card_last_four:
          label: "ending in"
          display_type: "masked"
          order: 3
      google_pay:
        wallet_type:
          label: ""
          display_type: "wallet_icon"
          order: 1
        card_brand:
          label: ""
          display_type: "brand_icon"
          order: 2
        card_last_four:
          label: "ending in"
          display_type: "masked"
          order: 3
      samsung_pay:
        wallet_type:
          label: ""
          display_type: "wallet_icon"
          order: 1
        card_brand:
          label: ""
          display_type: "brand_icon"
          order: 3
        card_last_four:
          label: "ending in"
          display_type: "masked"
          order: 3