spring:
  application:
    name: api
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      username: 
      password: ${REDIS_PASSWORD}
      timeout: 2000
  datasource:
    url: "jdbc:postgresql://${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DATABASE}"
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
server:
  port: 8080

cors:
  allowed-origins:
    - https://mc-host-web-production.up.railway.app
    - http://localhost:3000

hetzner:
  api-base: "https://api.hetzner.cloud/v1"
  api-token: ${HETZNER_SECRET_KEY}

clerk:
  key: ${CLERK_SECRET_KEY}

stripe:
  api-key: ${STRIPE_SECRET_KEY}
  signing-key: ${STRIPE_SECRET_SIGNING_KEY}
  active-java-product-id: prod_RiiVxhDuwyX0qD
  event-debounce-ttl-ms: 5000
  subscription-events:
    - checkout.session.completed
    - customer.subscription.created
    - customer.subscription.updated
    - customer.subscription.deleted
    - customer.subscription.paused
    - customer.subscription.resumed
    - customer.subscription.trial_will_end
    - customer.subscription.pending_update
    - customer.subscription.pending_update_applied
    - customer.subscription.pending_update_expired
    - invoice.paid
    - invoice.updated
    - invoice.payment_failed
    - invoice.payment_action_required
    - invoice.upcoming
    - invoice.marked_uncollectible
    - invoice.payment_succeeded
    - payment_intent.succeeded
    - payment_intent.payment_failed
    - payment_intent.canceled
  price-events:
    - price.created
    - price.deleted
    - price.updated
  
